### ISSUE TITLE
variant-based nonstd::optional public interface is empty

### ISSUE THREAD

**Issue by flexferrum** [martinmoene/variant-lite#19]
Current implementation of variant-based nonstd::optional is empty and useless. It's difficult to use both nonstd::optional and nonstd::variant in the one project due to header names ambiguity.

**Comment by martinmoene** [comment]
Indeed, a not-even half-hearted, wholly lost-sight of wack at it.

**Comment by martinmoene** [comment]
optional.hpp has been removed.
