### ISSUE TITLE
nonstd::visit does not work in VisualStudio

### ISSUE THREAD

**Issue by tower120** [martinmoene/variant-lite#2]
The following code does not compiles in Visual Studio 2017:
```C++
struct A {
	int x = 1;
};
struct B {
	int x = 2;
};
struct C {
	int x = 3;
};


nonstd::variant<A, B, C> v;

int main()
{
	v = A();
	nonstd::visit([](auto&& e) {
		
	}, v);

    return 0;
}
```

**Comment by martinmoene** [comment]
Note 1: visitor is limited to always return a Variant (just above [this](https://github.com/martinmoene/variant-lite#configuration-macros)).
```
nonstd::visit( [&](auto&& e){ return v; }, v );
```
Due to pre-C++17 language limitations (or mine), variant-lite's visitor must return the variant.

**Comment by tower120** [comment]
This is non standart-compatible behaviour. But I understood you.
