### ISSUE TITLE
Bug in CMakeLists.txt, include_source_dir not set

### ISSUE THREAD

**Issue by Manu343726** [martinmoene/variant-lite#25]
The cmake target references a `include_source_dir` variable as its include directories when building, variable that's not set in the script. This makes that the library include dir is not passed to the target.

``` cmake
project( variant_lite LANGUAGES CXX )

include( GNUInstallDirs )

set( package_name "variant-lite" )

# Interface library:

add_library(
    ${package_name} INTERFACE )

target_include_directories(
    ${package_name} INTERFACE "$<BUILD_INTERFACE:${include_source_dir}>" )
```

**Comment by martinmoene** [comment]
Fixed in 20d36d608377a7475c62573298c259073a97d8a9
