### ISSUE TITLE
`std::hash<nonstd::variant>` returns random value depends on uninitialized memory area.

### ISSUE THREAD

**Issue by tekezo** [martinmoene/variant-lite#32]
There is a problem that `std::hash<nonstd::variant>` does not return the same hash value for the same variant value.

## Version

Both variant-lite@1051f91afd28fdfc05b2d2b8d1a0359090aabe3e and v1.1.0.

## Example code

```c++
#define variant_CONFIG_SELECT_VARIANT variant_VARIANT_NONSTD

#include <cstdint>
#include <iostream>
#include <nonstd/variant.hpp>

int main(void) {
  using variant_t = nonstd::variant<uint32_t, uint64_t>;

  variant_t v1(static_cast<uint32_t>(42));

  variant_t v2(9223372036854775808ull);
  v2 = static_cast<uint32_t>(42);

  // std::hash<variant_t>{}(v1) should be equal std::hash<variant_t>{}(v2) since v1 == v2

  std::cout << "v1: " << std::hash<variant_t>{}(v1) << std::endl;
  std::cout << "v2: " << std::hash<variant_t>{}(v2) << std::endl;

  return 0;
}
```

## Actual result

(v1 != v2)

```
v1: 2269231707
v2: 2820897755
```

## Expected result

(v1 == v2)

```
v1: 2269231707
v2: 2269231707
```

## Note

I guess the `hash` is accessing uninitialized memory here.

https://github.com/martinmoene/variant-lite/blob/master/include/nonstd/variant.hpp#L832

**Comment by tekezo** [comment]
I confirmed the latest revision fixed this issue.
Thank you!

**Comment by martinmoene** [comment]
As @siffiejoe [notes](https://github.com/martinmoene/variant-lite/commit/716767efa60f7ba6fc9870a3d04274d22dd3e1f1#r32180859), `std::hash<nonstd::variant>` may well include padding bits in a variant alternative structure for the computation of the hash value. This can have a randomizing effect on the hash value.

The solution seems to be to require `std::hash<userdefined-struct>` to be available and use that.

**Comment by martinmoene** [comment]
Thanks @tekezo & s @siffiejoe.
