### ISSUE TITLE
Falling back to standard variant header for newer compilers

### ISSUE THREAD

**Issue by agauniyal** [martinmoene/variant-lite#4]
I see you've macro checks for c++ standards and a bunch of others for compilers and was wondering is it possible to fall back to standard headers if compilers provide them? This idea is somewhat similar to what abseil library does with their headers and I could've missed it if you already had a code in these headers for that 😅

**Comment by martinmoene** [comment]
Yeah, good idea, which I've only done for invoke-lite so far I see. I'll take a look at it.
